Pagina de Pedidos/Controllers/UsuarioController.cs
using Pagina_de_Pedidos.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pagina_de_Pedidos.Controllers
{
    public class UsuarioController : Controller
    {
        private PaginaPedidoEntities bd = new PaginaPedidoEntities();
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(string email, string contrasena)
        {
            var uss = bd.Usuario.FirstOrDefault(u => u.email == email && u.contrasena == contrasena);
            if (uss != null)
            {
                Session["Nombre"] = uss.nombre + " - " + uss.email;
                Session["iduss"] = uss.id_usuario;
                Session["tipoUss"] = uss.id_tipousuario;
                return RedirectToAction("Index", "Pedido");
            }
            return View();
        }
        public ActionResult Logout()
        {
            Session.Clear();
            Session.RemoveAll();
            Session.Abandon();
            return RedirectToAction("Login");
        }
        // MANTENEDOR CREAR
        public ActionResult Crear()
        {
            ViewBag.id_tipoUsuario = new SelectList(bd.TipoUsuario, "id_tipoUsuario", "nombre");
            return View();
        }
        [HttpPost]
        public ActionResult Crear(Usuario usuario)
        {
            bd.Usuario.Add(usuario);
            bd.SaveChanges();
            ViewBag.id_tipoUsuario = new SelectList(bd.TipoUsuario, "id_tipoUsuario", "nombre");
            return View();
        }
        public ActionResult Index()
        {
            var usuario = bd.Usuario.ToList();
            return View(usuario);
        }
        //MANTENEDOR EDITAR
        public ActionResult Editar(int? id)
        {
            if (id != null)
            {
                var usuario = bd.Usuario.Find(id);
                if (usuario != null)
                {
                    return View(usuario);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public ActionResult Editar(Usuario usuario)
        {
            bd.Entry(usuario).State = System.Data.EntityState.Modified;
            bd.SaveChanges();
            return RedirectToAction("Index");
        }
        //MANTENEDOR ELIMINAR
        public ActionResult Eliminar(int? id)
        {
            if (id != null)
            {
                var usuario = bd.Usuario.Find(id);
                if (usuario != null)
                {
                    return View(usuario);
                }
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Eliminar(int id_usuario)
        {
            var usuario = bd.Usuario.Find(id_usuario);
            if (usuario != null)
            {
                bd.Usuario.Remove(usuario);
                bd.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult RutExiste(string existe)
        {
            if (!string.IsNullOrEmpty(existe))
            {
                var q = bd.Usuario.FirstOrDefault(e => e.rut.ToLower().Equals(existe.ToLower()));
                if (q != null)
                {
                    string nombre = q.nombre;
                    return Json(nombre);
                }
            }
            return Json("");
        }
        public ActionResult EmailExiste(string existe)
        {
            if (!string.IsNullOrEmpty(existe))
            {
                var q = bd.Usuario.FirstOrDefault(e => e.email.ToLower().Equals(existe.ToLower()));
                if (q != null)
                {
                    string nombre = q.nombre;
                    return Json(nombre);
                }
            }
            return Json("");
        }
    }
}

Pagina de Pedidos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pagina de Pedidos</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @*<link href="~/Content/login.css" rel="stylesheet" />*@
    <link href="~/Content/estilos.css" rel="stylesheet" />
</head>
<body>
    @if (Session["iduss"] != null)
    {
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
        <div class="container-fluid header">
            <a class="navbar-brand pr-3" style="margin-right: 5rem;" href="/Pedido/Index/"><i class="fas fa-hotdog"></i> Pedidos Ñam</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    @*se puede usar con el nombre de tipousuario*@
                    @if (Session["tipouss"].ToString() == "1")
                    {

                        @Html.Partial("_menuAdmin");
                    }
                    @if (Session["tipouss"].ToString() == "2")
                    {

                        @Html.Partial("_menuVendedor");
                    }
                </ul>
                <div >
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item li">
                            <a class="nav-link active">@Session["Nombre"]</a>
                        </li>
                        <li class="nav-item li">
                            <a class="nav-link active" href="@Url.Action("Logout","Usuario")">Salir <i class="fa fa-power-off" aria-hidden="true"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/popper.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/sweetalert.min.js"></script>
    <div class="container-fluid body-content main">
        @RenderBody()
    </div>
    <footer class="bg-light text-center footer">
        <div class="h-100  d-flex justify-content-center align-items-center" style="background-color: rgba(0, 0, 0, 0.2);">
            <p>&copy; @DateTime.Now.Year - Copyright: Instituto Profesional Virgino Gómez</p>
        </div>
    </footer>      
    }else{
        Response.Redirect("~/Usuario/Login");
    }
</body>
</html>

Pagina de Pedidos/Views/Shared/_menuAdmin.cshtml
<li class="nav-item li">
    <a class="nav-link active" aria-current="page" href="/Categoria/Index/">Categorías</a>
</li>
<li class="nav-item li">
    <a class="nav-link active" aria-current="page" href="/Producto/Index/">Productos</a>
</li>
<li class="nav-item li">
    <a class="nav-link active" href="/Cliente/Index/">Clientes</a>
</li>
<li class="nav-item dropdown li">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Usuarios
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="/Usuario/Index/">Lista de Usuarios</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="/TipoUsuario/Index//">Tipos de Usuarios</a></li>
    </ul>
</li>
<li class="nav-item dropdown li">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Pedidos
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="/Pedido/Index/">Crear Pedido</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="/Pedido/HistorialPedido/">Listado de Pedidos</a></li>
    </ul>
</li>
<li class="nav-item li">
    <a class="nav-link active" href="/Detalle/Index/">Detalles</a>
</li>

Pagina de Pedidos/Views/Shared/_menuVendedor.cshtml
<li class="nav-item li">
    <a class="nav-link active" href="/Pedido/Index/">Crear pedido Pedidos</a>
</li><li class="nav-item li">
    <a class="nav-link active" href="/Pedido/HistorialPedido/">Historial Pedidos</a>
</li><li class="nav-item li">
    <a class="nav-link active" href="/Detalle/Index/">Historial detalles</a>
</li>